name: shepherdswatchfarm
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#006600'
    - '#cc9900'
    - '#ffffff'
    - '#747273'
  brandStrength: 0.75
  lightness: 0.7807483631186187
  saturation: 0.7658743527717888
  rhythmicContrast: 0.9444894653279334
purpose: []
