name: shepherdswatchfarm
favicon: null
layout_spectrum: 0.20626
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000033'
    - '#cc9900'
    - '#006600'
    - '#7f610f'
    - '#ff0000'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
