name: shepherdswatchfarm
favicon: null
layout_spectrum: 0.90142
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#006600'
    - '#cc9900'
    - '#ffffff'
    - '#747273'
  brandStrength: 1
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
